stages:
  - build
  - test
  - push-image

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  before_script:
    - "dotnet restore"
  script:
    - "dotnet build"

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  services:
    - docker:18.09.7-dind
  before_script:
    - "dotnet restore"
  script:
    - "dotnet test"

push-image:
  stage: push-image
  image: docker:latest
  services:
    - docker:18.09.7-dind
  script:
    - echo -n $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin $DOCKER
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE"
  only:
    - dev
    - master
