stages:
  - build
  # - test
  - deploy 

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  before_script:
    - "dotnet restore"
  script:
    - "dotnet build"

# test:
#   stage: test
#   image: mcr.microsoft.com/dotnet/sdk:5.0
#   before_script:
#     - "dotnet restore"
#   script:
#     - "dotnet test"

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - $DOCKER_PASS | docker login -u "$DOCKER_USER" --password-stdin $DOCKER
  script:
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE"
