stages:
  - build
  - test
  - push-image 
  - deploy-production

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  before_script:
    - "dotnet restore"
  script:
    - "dotnet build"

# test:
#   stage: test
#   image: mcr.microsoft.com/dotnet/sdk:5.0
#   services:
#     - docker:dind
#   before_script:
#     - "dotnet restore"
#   script:
#     - "dotnet test"

push-image:
  stage: push-image
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" $DOCKER
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE"
  only:
    - dev
    - master

deploy-production:
  stage: deploy-production
  script:
    - ssh -o StrictHostKeyChecking=no root@45.79.198.133 "/bin/python3 ./deploy_app.py"