stages:
  - build
  # - test
  - deploy_dev
  - deploy_prod

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  before_script:
    - "dotnet restore"
  script:
    - "dotnet build"

# test:
#   stage: test
#   image: mcr.microsoft.com/dotnet/sdk:5.0
#   before_script:
#     - "dotnet restore"
#   script:
#     - "dotnet test"

deploy_dev:
  stage: deploy_dev
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" $DOCKER
    - docker build -t "$DOCKER_IMAGE" --build-arg ASP_ENV=dev .
    - docker push "$DOCKER_IMAGE:beta"
  only:
    - dev

deploy_prod:
  stage: deploy_prod
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" $DOCKER
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE"
  only:
    - master
