// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingTrackAPI.Models;

namespace ShoppingTrackAPI.Migrations
{
    [DbContext(typeof(ShoppingTrackContext))]
    [Migration("20220228004642_UpdateNamingAndProperties")]
    partial class UpdateNamingAndProperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShoppingTrackAPI.Models.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("CallStack")
                        .IsRequired()
                        .HasColumnName("call_stack")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnName("location")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLog");
                });

            modelBuilder.Entity("ShoppingTrackAPI.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CurrentStoreId")
                        .HasColumnName("currentStoreId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LastStoreId")
                        .HasColumnName("last_store_id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(250)");

                    b.Property<decimal?>("PreviousPrice")
                        .HasColumnName("previous_price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<ulong>("Purchased")
                        .HasColumnName("purchased")
                        .HasColumnType("bit(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ShoppingTrackAPI.Models.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnName("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DateOfPrice")
                        .HasColumnName("DateOfPrice")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ItemId")
                        .HasColumnName("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("StoreId")
                        .HasColumnName("StoreId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("ShoppingTrackAPI.Models.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0001"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(2197),
                            IsDeleted = false,
                            Name = "Kroger"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0002"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(4855),
                            IsDeleted = false,
                            Name = "Publix"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0003"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(4942),
                            IsDeleted = false,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0004"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(4989),
                            IsDeleted = false,
                            Name = "Whole Foods"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0005"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5031),
                            IsDeleted = false,
                            Name = "Trader Joes"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0006"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5073),
                            IsDeleted = false,
                            Name = "Walmart"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0007"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5115),
                            IsDeleted = false,
                            Name = "Dollar General"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0008"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5157),
                            IsDeleted = false,
                            Name = "Pick n Save"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0009"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5201),
                            IsDeleted = false,
                            Name = "Giant Eagle"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0010"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5243),
                            IsDeleted = false,
                            Name = "Schnucks"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0011"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5284),
                            IsDeleted = false,
                            Name = "H-E-B"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0012"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5326),
                            IsDeleted = false,
                            Name = "Food Lion"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0013"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5368),
                            IsDeleted = false,
                            Name = "Costco"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0014"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5409),
                            IsDeleted = false,
                            Name = "Sams Club"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0015"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5451),
                            IsDeleted = false,
                            Name = "ALDI"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0016"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5492),
                            IsDeleted = false,
                            Name = "Save A Lot"
                        },
                        new
                        {
                            Id = new Guid("f19b1ffb-cfc1-40cf-9b71-5a9b702e0017"),
                            CreatedDate = new DateTime(2022, 2, 28, 0, 46, 41, 835, DateTimeKind.Utc).AddTicks(5534),
                            IsDeleted = false,
                            Name = "Orbit Health"
                        });
                });

            modelBuilder.Entity("ShoppingTrackAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<ulong>("Admin")
                        .HasColumnName("admin")
                        .HasColumnType("bit(1)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasColumnType("varchar(16)");

                    b.Property<ulong>("Validated")
                        .HasColumnName("validated")
                        .HasColumnType("bit(1)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
