name: Build/Tests (CI)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '5.0.x'
      - run: dotnet restore
      - run: dotnet build

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x scripts/build.sh
      - run: docker run --network="host" -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/app mcr.microsoft.com/dotnet/sdk:5.0 ./app/scripts/build.sh

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: cd ShoppingTrackAPIUnitTest
      - run: dotnet restore
      - run: dotnet test